# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e27d0f4f926262b961c8ed33c4b0ae6dd93035699e59517e98110d407f87009623801329ee6483c4f937b55bc56ffaa49e03e64e99acb1d926c42ba1688efe9f

test:
  secret_key_base: 6f912774b240fac6983a581b825225386b2a581fba318ab7aa933728d0f063f49be027b3448c99e2e12f2ff887ae8b24f5bcc99fe364aa5a402db3e1fec97574

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
