# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70823761fb0e9bdff7341fc6e7d436ffd35b864915c3f51be5d6f5ac39a50432cc98e7c3ca2b78ba19fd89b4d120173263b8c7f5b1427451a31a3d96ad5788cd

test:
  secret_key_base: eb80f1887cc730ff3af73be124109985398057aa87ded8d924d40b5c545ce9b60f003d747ed7c0aa387b27cf9944be7f1ce424939da274490083eb3b33a2a3fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
